spring:
  application:
    name: Backend
  datasource:
    url: jdbc:mysql://localhost:3306/fashion
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  main:
    allow-bean-definition-overriding: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
server:
  servlet:
    encoding:
      charset: UTF-8
logging:
  level:
    root: debug
gmail:
  username: nguyenlengocmai000@gmail.com
  password: dprj oedn kkid eqoj
sms:
  speedsms:
    apiKey: 3c-XvSUYNwsIv9P2qOBBqUsL3b4hKBJH
    phone: 0585885214